typo修正
senbei-holdings/senbei-holdings.github.io pull request #16
Opened 2020-05-29 10:40 UTC by seibe2

typoを直し、正しい社名に直しました。

2020-05-29 10:41 UTC, highemerly requested changes
会社名が誤っています

2020-05-29 10:41 UTC, highemerly commented on index.html
> +        <p class="jis">Welcome to Seibe Holdings!</p>
Senbei Holdings だと思います

2020-05-29 10:57 UTC, seibe2 commented on index.html
> +        <p class="jis">Welcome to Seibe Holdings!</p>
https://twitter.com/seibe48 こちらのとおり「せいべHD（ホールディングス）」となります。

2020-05-29 11:11 UTC, highemerly commented on index.html
> +        <p class="jis">Welcome to Seibe Holdings!</p>
せんべいHD（ホールディングス）になっているようですが？

2020-05-29 11:23 UTC, seibe2 commented on index.html
> +        <p class="jis">Welcome to Seibe Holdings!</p>
こちらの結果の通り、せいべHD 100%となります。
https://handon.club/web/statuses/104251408951563341

2020-05-29 14:53 UTC, highemerly commented
コンフリクトが発生しているため修正お願いします。

2020-05-30 12:20 UTC, seibe2 commented
コンフリクト解消していると思われます

2020-05-30 12:40 UTC, highemerly approved these changes

2020-05-30 12:40 UTC, merged